[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "fpdf2>=2.8.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "streamlit>=1.48.0",
    "xlsxwriter>=3.2.5",
]
