# ============================================================================
# Restaurant Ingredient Tracker - CPU Compatible Docker Compose
# ============================================================================
# This configuration is specifically for CPUs with only SSE4a support
# (no SSE4.1/SSE4.2/AVX) to avoid "Illegal instruction (core dumped)" errors

version: '3.8'

services:
  restaurant-tracker:
    build:
      context: ..
      dockerfile: Docker Deployment/Dockerfile.cpu-compatible
      target: production
      args:
        APP_USER: streamlit
        APP_UID: 1000
        APP_GID: 1000
    container_name: restaurant-tracker-cpu-compatible
    
    # Platform specification for compatibility
    platform: linux/amd64
    
    # Environment configuration
    environment:
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      
      # Force CPU-only mode for numerical libraries
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - OMP_NUM_THREADS=1
      
      # Disable vectorized operations that might use newer instructions
      - NUMBA_DISABLE_JIT=1
      
      # Application Configuration
      - APP_ENV=production
      - ENABLE_DEMO_MODE=true
      
      # Performance Configuration
      - PYTHONHASHSEED=random
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    
    # Port mapping
    ports:
      - "8501:8501"
    
    # Volume mounts for data persistence
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./exports:/app/exports:rw
    
    # Health check configuration with longer startup time
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s  # Longer startup time for CPU-compatible build
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits - more generous for CPU compilation
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Labels
    labels:
      - "com.restaurant-tracker.service=webapp-cpu-compatible"
      - "com.restaurant-tracker.version=1.0"
      - "com.restaurant-tracker.cpu-support=sse4a-only"