name = "restaurant-ingredient-tracker"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "DATA_STORE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[env.dev]
vars = { NODE_ENV = "development" }

[env.production] 
vars = { NODE_ENV = "production" }